openapiOptions:
  file:
    - file: "orderingpb/api.proto"
      option:
        info:
          title: Order Processing
          version: "1.0.0"
        basePath: /
  method:
    - method: orderingpb.OrderingService.CreateOrder
      option:
        operationId: createOrder
        tags:
          - Order
        summary: Start a new order
    - method: orderingpb.OrderingService.GetOrder
      option:
        operationId: getOrder
        tags:
          - Order
        summary: Get an order
    - method: orderingpb.OrderingService.CancelOrder
      option:
        operationId: cancelOrder
        tags:
          - Order
        summary: Cancel an order

    - method: orderingpb.OrderingService.GetAll
      option:
        operationId: GetAll
        tags:
          - Order
        summary: Get all orders

    - method: orderingpb.OrderingService.RemoveIds
      option:
        operationId: Delete Orders
        tags:
          - Order
        summary: Delete Orders by Id's
